export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Plan your day",
  headline: "With 0 effort and 100% results",
  description:
    "Just add events and tasks for the whole day and algorithm will help you adjust them better!",
  buttonLabel: "Get Started",
  imgStart: false,
  img: require("../../images/svg-1.svg").default,
  alt: "Calendar",
  dark: true,
  primary: true,
  darkText: false,
  to: "/home",
};

export const homeObjTwo = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Review stats",
  headline: "Get to know your full of activities months",
  description:
    "Visualized statistics will help you figure out your daily activity. Get all stats by clicking just one button!",
  buttonLabel: "Learn More",
  imgStart: true,
  img: require("../../images/svg-2.svg").default,
  alt: "Statistics",
  dark: false,
  primary: false,
  darkText: true,
  to: "/discover",
};

export const homeObjThree = {
  id: "signup",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Join us",
  headline: "Creating an account is extremely easy",
  description: "Just fill in 3 fields and you are done!",
  buttonLabel: "Sign Up",
  imgStart: false,
  img: require("../../images/svg-3.svg").default,
  alt: "Join",
  dark: true,
  primary: true,
  darkText: false,
  to: "/signup",
};
