# Generated by Django 3.1.2 on 2022-05-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='id_token',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='refresh_token',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='access_token',
            field=models.TextField(max_length=2048, null=True),
        ),
    ]
